apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: metrics-server-monitor-prometheus
  name: metrics-server-monitor-prometheus
  namespace: default
spec:
  endpoints:
  - interval: 30s
    port: metrics
    scheme: http
  namespaceSelector:
    matchNames:
    - default
  selector:
    matchLabels:
      k8s-app: metrics-server-monitor-prometheus
